apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
metadata:
        name: scheduler-extender-config
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
algorithmSource:
  policy:
    file:
      path: "/etc/kubernetes/scheduler-extender-policy.json"
      # YAML not supported yet
      # https://github.com/kubernetes/kubernetes/issues/75852
